#!/bin/bash

# 从 Obsidian md 文档中更新 hexo-butterfly-demo 的 README.md 文档

readme_fn="README.md"
repo_path="$HOME/scripts/sites/hexo-butterfly-demo"
readme_path="${repo_path}/${readme_fn}"

obsd_md_path="${HOME}/scripts/obsidian-md"
if [[ $HOSTNAME =~ "DESKTOP" ]]; then
  obsd_md_path="/mnt/e/obsidian-md"
elif [[ $HOSTNAME =~ "LAPTOP" ]]; then
  obsd_md_path="/mnt/d/obsidian-md"
fi

obsd_readme="${obsd_md_path}/blog/hexo.md"

cp "${obsd_readme}" "${readme_path}"

git_update() {
  git status --short --branch
  echo
  git add "${readme_fn}"
  git commit -m "update ${readme_fn}"
  echo
}

update_num() {
  cd "${repo_path}" || exit

  update_md_num=$(git status --short --branch | grep -c "${readme_fn}")

  if [[ $update_md_num -eq 0 ]]; then
    echo -e "\n${readme_fn} is latest."
  else
    echo -e "\n${readme_fn} is updated."
    git_update
  fi

  cd - >/dev/null 2>&1 || exit
}

update_num
