#!/bin/bash

# 从 Obsidian md 文档中更新 mkdocs-demo 的 notes md 文档

repo_path="$HOME/scripts/sites/mkdocs-demo"
post_md_path="${repo_path}/docs"
# echo $(ls $post_md_path)

post_md_files=$(find ${post_md_path} -type f -name "*.md")
# echo $post_md_files

obsd_md_path="${HOME}/scripts/obsidian-md"
if [[ $HOSTNAME =~ "DESKTOP" ]]; then
    obsd_md_path="/mnt/e/obsidian-md"
elif [[ $HOSTNAME =~ "LAPTOP" ]]; then
    obsd_md_path="/mnt/d/obsidian-md"
fi

obsd_md_files=$(find ${obsd_md_path} -type f -name "*.md")
# echo $obsd_md_files

for post_md in $post_md_files; do
    post_md_name=$(basename $post_md)

    if [[ ! $post_md_name =~ "index.md" ]]; then
        for obsd_md in $obsd_md_files; do
            obsd_md_name=$(basename $obsd_md)

            if [[ $post_md_name == $obsd_md_name ]]; then
                # echo "cp $obsd_md to ${post_md}"
                cp ${obsd_md} ${post_md}
            fi
        done
    fi
done


git_update(){
    BRANCH=$(git branch --show-current)
    git status --short --branch
    echo
    git add ${post_md_path}
    git commit -m "update post mds"
    echo
    # git push origin ${BRANCH}
}


update_num(){
    cd ${repo_path}

    update_md_num=$(git status --short --branch | grep -E "\.md$" | wc -l)

    if [[ $update_md_num -eq 0 ]]; then
        echo -e "\nNo post md files are updated."
    else
        echo -e "\n${update_md_num} post md file(s) is(are) updated."
        git_update
    fi

    cd - > /dev/null 2>&1 
}


update_num
