#!/bin/bash

# 用 rsync 从 Obsidian md 文档中更新 hexo-butterfly-demo 的 posts md 文档

post_folders=(
    blog
    linux
    markup
    programming
    scitoolkits
    PhD/sjtu
    win-softwares
)

repo_path="$HOME/scripts/sites/hexo-butterfly-demo"

obsd_path="${HOME}/scripts/obsidian-md"
if [[ $HOSTNAME =~ "DESKTOP" ]]; then
    obsd_path="/mnt/e/obsidian-md"
elif [[ $HOSTNAME =~ "LAPTOP" ]]; then
    obsd_path="/mnt/d/obsidian-md"
fi

for post_folder in "${post_folders[@]}"; do
    obsd_md_path="${obsd_path}/${post_folder}"
    post_md_path="${repo_path}/source/_posts"

    rsync -avuP --existing "${obsd_md_path}" "${post_md_path}"
done


git_update(){
    git status --short --branch
    echo
    git add "${post_md_path}"
    git commit -m "update post mds"
    echo
}


update_num(){
    cd "${repo_path}" || exit

    update_md_num=$(git status --short --branch | grep -c "\.md$")

    if [[ $update_md_num -eq 0 ]]; then
        echo -e "\nNo post md files are updated."
    else
        echo -e "\n${update_md_num} post md file(s) is(are) updated."
        git_update
    fi

    cd - > /dev/null 2>&1  || exit
}


update_num
