#!/bin/bash

# 从 Obsidian md 文档中更新 hexo-butterfly-demo 的 notes md 文档

repo_path="$HOME/scripts/sites/hexo-butterfly-demo"
post_md_path="${repo_path}/source/_posts"

obsd_md_path="${HOME}/scripts/obsidian-md"
if [[ $HOSTNAME =~ "DESKTOP" ]]; then
    obsd_md_path="/mnt/e/obsidian-md"
elif [[ $HOSTNAME =~ "LAPTOP" ]]; then
    obsd_md_path="/mnt/d/obsidian-md"
fi

obsd_md_files=$(find ${obsd_md_path} -type f -name "*.md")

for post_md in $(ls $post_md_path); do
    for obsd_md in $obsd_md_files; do
        if [[ $post_md == $(basename $obsd_md) ]]; then
            # echo "cp $(basename $obsd_md) to ${post_md}"
            cp ${obsd_md} ${post_md_path}
        fi
    done
done


git_update(){
    BRANCH=$(git branch --show-current)
    git status --short --branch
    echo
    git add ${post_md_path}
    git commit -m "update post mds"
    echo
    # git push origin ${BRANCH}
}


update_num(){
    cd ${repo_path}

    update_md_num=$(git status --short --branch | grep -E "\.md$" | wc -l)

    if [[ $update_md_num -eq 0 ]]; then
        echo "No post md files are updated."
    else
        echo -e "${update_md_num} post md file(s) is(are) updated.\n"
        git_update
    fi

    cd - > /dev/null 2>&1 
}


update_num
